// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCV85ixugSpbW_5XbySFy9vv6i_nXsYnXA',
    appId: '1:198736972058:web:07a1d08cf58b279360c4a3',
    messagingSenderId: '198736972058',
    projectId: 'chatauth-48514',
    authDomain: 'chatauth-48514.firebaseapp.com',
    storageBucket: 'chatauth-48514.appspot.com',
    databaseURL: "https://chatauth-48514-default-rtdb.asia-southeast1.firebasedatabase.app",
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV85ixugSpbW_5XbySFy9vv6i_nXsYnXA',
    appId: '1:198736972058:web:07a1d08cf58b279360c4a3',
    messagingSenderId: '198736972058',
    projectId: 'chatauth-48514',
    authDomain: 'chatauth-48514.firebaseapp.com',
    storageBucket: 'chatauth-48514.appspot.com',
    databaseURL: "https://chatauth-48514-default-rtdb.asia-southeast1.firebasedatabase.app",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSebEq2KGPl0EeDqgMpSOuCnhMHXtm9EE',
    appId: '1:198736972058:android:98dbe8446582858060c4a3',
    messagingSenderId: '198736972058',
    projectId: 'chatauth-48514',
    storageBucket: 'chatauth-48514.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhbqCxz2pqI0FTht0cC6YCMFdo8psOq2k',
    appId: '1:198736972058:ios:dec007851cd66b8c60c4a3',
    messagingSenderId: '198736972058',
    projectId: 'chatauth-48514',
    storageBucket: 'chatauth-48514.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhbqCxz2pqI0FTht0cC6YCMFdo8psOq2k',
    appId: '1:198736972058:ios:c571838d10253afb60c4a3',
    messagingSenderId: '198736972058',
    projectId: 'chatauth-48514',
    storageBucket: 'chatauth-48514.appspot.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
